"""WebSocket endpoint that spawns a coding agent CLI session (Claude Code or OpenCode) with MCP tools."""

import asyncio
import json
import os
import pty
import select
import shutil
import struct
import subprocess
import fcntl
import termios
from pathlib import Path

import aiosqlite
from fastapi import APIRouter, WebSocket, WebSocketDisconnect, Query

from src.backend.config import get_settings
from src.backend.database import get_connection

router = APIRouter(tags=["terminal"])

PROJECT_ROOT = Path(__file__).parent.parent.parent.parent
DATA_DIR = PROJECT_ROOT / "data"


def _claude_sessions_dir() -> Path:
    """Where Claude Code stores per-project session .jsonl files."""
    encoded = str(PROJECT_ROOT.resolve()).replace("/", "-")
    return Path.home() / ".claude" / "projects" / encoded


def _list_session_uuids() -> set[str]:
    d = _claude_sessions_dir()
    if not d.exists():
        return set()
    return {p.stem for p in d.glob("*.jsonl")}


async def _detect_new_session(
    pre: set[str],
    sketch_id: int,
    deadline_seconds: float = 8.0,
):
    """Poll the Claude sessions dir for a new .jsonl file and save its uuid to the sketch."""
    settings = get_settings()
    elapsed = 0.0
    while elapsed < deadline_seconds:
        await asyncio.sleep(0.5)
        elapsed += 0.5
        current = _list_session_uuids()
        new_ids = current - pre
        if new_ids:
            session_id = sorted(new_ids)[0]  # 보통 1개
            db = await get_connection(settings.db_path)
            try:
                await db.execute(
                    "UPDATE sketches SET claude_session_id = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND claude_session_id IS NULL",
                    (session_id, sketch_id),
                )
                await db.commit()
            finally:
                await db.close()
            return


async def _get_sketch_session(sketch_id: int) -> str | None:
    settings = get_settings()
    db = await get_connection(settings.db_path)
    try:
        cursor = await db.execute(
            "SELECT claude_session_id FROM sketches WHERE id = ?", (sketch_id,)
        )
        row = await cursor.fetchone()
        return row["claude_session_id"] if row else None
    finally:
        await db.close()


def _find_python() -> tuple[str, list[str]]:
    """Return (command, base_args) for running our MCP server."""
    venv_python = PROJECT_ROOT.resolve() / ".venv" / "bin" / "python"
    if venv_python.exists():
        return str(venv_python), ["-m", "src.backend.mcp_server.server"]
    return "uv", ["run", "python", "-m", "src.backend.mcp_server.server"]


def _ensure_claude_mcp_config() -> Path:
    """Generate Claude Code MCP config (mcpServers format)."""
    command, args = _find_python()
    config = {
        "mcpServers": {
            "dojang": {
                "command": command,
                "args": args,
                "cwd": str(PROJECT_ROOT.resolve()),
            }
        }
    }
    path = DATA_DIR / "mcp_config.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(config, indent=2))
    return path


def _ensure_opencode_config() -> Path:
    """Generate opencode.json in project root (mcp format for OpenCode)."""
    command, args = _find_python()
    config = {
        "mcp": {
            "dojang": {
                "type": "local",
                "command": [command, *args],
                "enabled": True,
            }
        }
    }
    path = PROJECT_ROOT / "opencode.json"
    path.write_text(json.dumps(config, indent=2))
    return path


# ---------------------------------------------------------------------------
# tmux wrapping for sketch terminals
#
# Sketch 터미널은 탭을 떠나면 WebSocket 이 끊기고, 돌아오면 새 WS 가 연결된다.
# tmux 로 감싸면 (a) 스크롤백이 보존되고, (b) 탭 떠나있는 동안에도 claude 가
# 계속 일할 수 있다 (긴 답변/도구 호출이 중단되지 않음).
#
# 격리된 소켓 (-L dojang) 을 써서 혹시 호스트에 떠있는 다른 tmux 와 섞이지
# 않게 한다. 키바인딩은 전부 unbind 해서 "투명 래퍼" 로 동작하도록.
# ---------------------------------------------------------------------------

_TMUX_SOCKET = "dojang"
_TMUX_CONF_PATH = DATA_DIR / "tmux.conf"
_TMUX_CONF = """# auto-generated by Dojang backend
set -g prefix None
unbind-key -a
set -g status off
set -sg escape-time 0
set -g default-terminal "xterm-256color"
set -g history-limit 50000
# mouse 는 끔 — 켜면 tmux 가 drag 이벤트까지 가로채 xterm 에서 텍스트 선택
# (/login URL 복사 등) 이 불가능해진다. 휠 스크롤은 프론트엔드 TerminalPanel
# 의 custom onWheel 핸들러가 로컬 xterm scrollback 으로 처리해서 화살표키
# 대신 실제 스크롤이 되게 한다.
set -g mouse off
set-window-option -g aggressive-resize on
"""


def _ensure_tmux_conf() -> Path:
    _TMUX_CONF_PATH.parent.mkdir(parents=True, exist_ok=True)
    if not _TMUX_CONF_PATH.exists() or _TMUX_CONF_PATH.read_text() != _TMUX_CONF:
        _TMUX_CONF_PATH.write_text(_TMUX_CONF)
    return _TMUX_CONF_PATH


def _tmux_base_cmd() -> list[str]:
    return ["tmux", "-L", _TMUX_SOCKET, "-f", str(_ensure_tmux_conf())]


def _tmux_has_session(name: str) -> bool:
    result = subprocess.run(
        _tmux_base_cmd() + ["has-session", "-t", name],
        capture_output=True,
    )
    return result.returncode == 0


def _tmux_sketch_session_name(sketch_id: int) -> str:
    return f"dojang-sketch-{sketch_id}"


def _tmux_curriculum_session_name(curriculum_id: int) -> str:
    """Learn 탭의 글로벌 dock 은 선택된 curriculum 단위로 tmux 세션을 가진다.
    topic 을 바꾸면 cascading 으로 curriculum 이 바뀌고 → 여기서 이름이 달라져서
    자연스럽게 새 세션으로 전환된다."""
    return f"dojang-curriculum-{curriculum_id}"


# 컨테이너의 Claude Code 세션이 /app/CLAUDE.md 를 자동으로 시스템 프롬프트에
# 주입받도록 한다 — 세션이 "맥락" 질문을 받았을 때 data/current_context.md 를
# 읽어 학습자가 지금 뭘 보고 있는지 답하게 만드는 게 목적.
_CLAUDE_MD_MARKER = "<!-- auto-generated by Dojang backend -->"
_CLAUDE_MD_CONTENT = f"""{_CLAUDE_MD_MARKER}

# Dojang 세션

여기는 Dojang 학습 플랫폼 안에서 돌고 있는 Claude Code 세션입니다. 학습자는
sketch 노트, 연습문제, 지식 카드 같은 걸 열어놓고 당신과 대화합니다.

## 학습자의 현재 맥락 (중요)

학습자가 프론트엔드에서 지금 보고 있는 항목은 `data/current_context.md` 파일에
자동으로 기록됩니다. 다음 상황에서는 반드시 먼저 이 파일을 `Read` 로 읽어서
학습자의 현재 맥락을 확인하세요:

- 새 대화가 시작될 때 (첫 유저 메시지 직후)
- 사용자가 "맥락", "context", "지금 뭐 보고 있어" 처럼 현재 상황을 물을 때
- 사용자가 "이거", "이 문제", "여기" 같이 지시대명사로 무언가를 가리킬 때

파일 포맷:
- `@curriculum:<제목> #<id> (topic: <토픽명>)` — 학습자가 Learn 탭에서 선택한
  커리큘럼. 구체 항목을 아직 안 눌렀어도 이 줄은 있을 수 있습니다. 커리큘럼
  전체 맥락을 보려면 `get_curriculum` MCP 도구로 트리를 가져오세요.
- `@sketch:<제목> #<id>` + 본문 — 학습자가 열어둔 sketch 노트
- `@exercise:<제목> #<id>` — 학습자가 클릭한 연습문제
- `@knowledge:<제목> #<id>` — 학습자가 클릭한 지식 카드
- `> <인용>` — 학습자가 드래그해서 추가한 관심 포인트

여러 줄이 같이 있을 수 있습니다. 예를 들어 `@curriculum:...` 과 `@exercise:...`
이 함께 있으면 "이 커리큘럼 안의 이 문제를 보고 있다" 는 뜻입니다.

파일이 비어있으면 지금 활성 맥락이 없다는 뜻입니다.

## MCP 도구 (dojang 서버)

커리큘럼/연습문제/지식을 조작할 때는 `dojang` MCP 서버의 도구를 쓰세요:
`get_curriculum`, `add_subject`, `create_exercise`, `create_curriculum`,
`save_knowledge`, `list_knowledge`, `review_curriculum`, `execute_code`,
`get_progress`. 데이터 변경 후 UI 갱신은 각 도구가 내부적으로 처리하므로
별도 알림 호출은 필요 없어요.

## 커리큘럼을 새로 만들 때 (중요)

사용자가 "X 커리큘럼 만들어줘" / "X 가르쳐줘" / "X 배우고 싶어" 같은 요청을
했을 때, **절대 한 번에 모든 걸 만들지 마세요**. 3단계로 진행합니다.

### 1단계 — 목차 먼저 제안 (MCP 도구 호출 금지)

먼저 대략적인 구조를 텍스트로 제안하고 사용자의 승인을 받으세요:
- **3~4개의 Part** 로 묶기 (예: "Part I. 기초" → "Part II. 핵심" → "Part III. 실전")
- 각 Part 아래 **3~5개 subject**
- 총 subject 수는 대략 10~15개 사이
- 이 단계에서 `create_curriculum` / `add_subject` 를 부르면 안 됩니다
- "이 구조 어때요? 대상 수준이나 분량 조절이 필요하면 말씀해주세요" 로 마무리

### 2단계 — 확정 후 실제 생성

사용자가 구조를 승인하면:

1. `create_curriculum` 으로 커리큘럼 컨테이너 생성
2. 각 Part 를 `add_subject(parent_id=None)` 로 생성 — 이게 상위 subject
3. 각 Part 아래에 학습 주제를 `add_subject(parent_id=<part 의 id>)` 로 생성
4. 각 학습 subject 마다:
   - `save_knowledge` 로 **2~4개** 지식 카드. 서로 다른 각도로:
     *개념 정의 / 왜 그렇게 설계됐나 / 어떻게 동작하나 / 흔한 함정* 중 골라쓰기.
     한 카드에 모든 걸 욱여넣지 말고 각도별로 분리.
   - `create_exercise` 로 **2~3개** 연습문제를 ladder 로:
     - drill (`check_type="output_match"`, `difficulty=1`): 개념 확인 드릴
     - apply (`check_type="ai_check"`, `difficulty=2`): 실제 상황 적용
     - extend (`check_type="ai_check"`, `difficulty=3`, 선택): 응용/변형

### 3단계 — 자기 점검 (필수)

생성이 끝나면 **반드시** `review_curriculum(curriculum_id=<방금 만든 id>)`
를 호출하세요. 반환되는 `warnings` 배열이 비어있지 않으면 지적된 문제를
보강한 뒤 다시 review 하세요. "Looks good" 하나만 나올 때까지 반복.

품질 기준 요약:
- parent_id 가 있는 subject 가 없는 subject 보다 많아야 함 (= 계층이 존재)
- 리프 subject 당 knowledge ≥ 2, exercise ≥ 2
- 난이도와 check_type 에 다양성

기존 CLI / Git / Docker / SQL 커리큘럼은 이 원칙 이전에 만들어진 flat 구조
입니다. 앞으로 만드는 커리큘럼이 같은 실수를 반복하지 않게 해주세요.
"""


def _ensure_container_claude_md() -> None:
    """컨테이너 안에서 돌 때만 /app/CLAUDE.md 를 써서 Claude Code 에게
    `data/current_context.md` 의 존재를 알려준다. 호스트 (레포 루트) 에는
    이미 프로젝트용 CLAUDE.md 가 있으므로, PROJECT_ROOT 가 /app 인 경우에만
    작동시켜 덮어쓰기를 방지한다. 또한 마커가 없는 기존 파일은 건드리지 않는다.
    """
    if str(PROJECT_ROOT) != "/app":
        return
    target = PROJECT_ROOT / "CLAUDE.md"
    if target.exists():
        existing = target.read_text()
        if not existing.startswith(_CLAUDE_MD_MARKER):
            return  # 사람이 쓴 CLAUDE.md 는 손대지 않음
        if existing == _CLAUDE_MD_CONTENT:
            return  # 이미 최신
    target.write_text(_CLAUDE_MD_CONTENT)


def _build_spawn_command(
    agent: str,
    sketch_id: int | None = None,
    curriculum_id: int | None = None,
    resume_session: str | None = None,
    bypass: bool = False,
) -> list[str]:
    """Return the CLI command to spawn for the given agent type.

    sketch_id 나 curriculum_id 가 있으면 tmux 로 감싸서 WS 재연결 사이에 세션과
    스크롤백이 유지되게 한다. sketch 가 curriculum 보다 우선 (sketch 탭은 sketch
    세션만 가지면 됨). 둘 다 없으면 tmux 없이 일반 claude 프로세스로 돌림.

    bypass=True 면 `--dangerously-skip-permissions` 를 붙여서 모든 권한 확인을
    건너뛴다 (Claude Code 의 bypass permissions 모드). 새로 spawn 하는 경우에만
    반영되고, 이미 살아있는 tmux 세션에 attach 할 때는 효과가 없다.
    """
    if agent == "opencode":
        _ensure_opencode_config()
        return ["opencode"]

    _ensure_container_claude_md()
    mcp_config = _ensure_claude_mcp_config()
    claude_cmd = ["claude", "--mcp-config", str(mcp_config)]
    if bypass:
        claude_cmd.append("--dangerously-skip-permissions")
    if resume_session:
        claude_cmd += ["--resume", resume_session]

    session_name: str | None = None
    if sketch_id is not None:
        session_name = _tmux_sketch_session_name(sketch_id)
    elif curriculum_id is not None:
        session_name = _tmux_curriculum_session_name(curriculum_id)

    if session_name is None:
        return claude_cmd

    if _tmux_has_session(session_name):
        # 살아있는 tmux 세션 재접속 — 다른 client 는 강제 detach (-d) 해서
        # 동시 접속으로 인한 이상한 리사이즈 방지.
        return _tmux_base_cmd() + ["attach-session", "-d", "-t", session_name]

    # 첫 연결 or tmux 서버 재시작 후 — claude 를 새 tmux 세션 안에서 띄운다.
    return _tmux_base_cmd() + ["new-session", "-s", session_name, *claude_cmd]


@router.get("/api/agents")
async def list_agents():
    """Return available agents and their install status."""
    agents = []
    for name, cmd in [("claude", "claude"), ("opencode", "opencode")]:
        agents.append({
            "id": name,
            "label": "Claude Code" if name == "claude" else "OpenCode",
            "installed": shutil.which(cmd) is not None,
        })
    return agents


@router.websocket("/ws/terminal")
async def terminal_websocket(
    ws: WebSocket,
    agent: str = Query(default="claude"),
    sketch_id: int | None = Query(default=None),
    curriculum_id: int | None = Query(default=None),
    bypass: bool = Query(default=False),
):
    await ws.accept()

    if agent not in ("claude", "opencode"):
        await ws.close(code=4000, reason=f"Unknown agent: {agent}")
        return

    # Per-scope session tracking (claude only). sketch_id 가 우선 — Sketch 탭은
    # curriculum 무관. curriculum_id 는 Learn / Subjects / Explore 탭의 글로벌
    # dock 에서만 설정된다.
    resume_session: str | None = None
    pre_sessions: set[str] = set()
    detect_task: asyncio.Task | None = None
    tmux_session_name: str | None = None
    if agent == "claude":
        if sketch_id is not None:
            resume_session = await _get_sketch_session(sketch_id)
            if resume_session is None:
                pre_sessions = _list_session_uuids()  # 새 세션이면 spawn 후 diff로 잡음
            tmux_session_name = _tmux_sketch_session_name(sketch_id)
        elif curriculum_id is not None:
            tmux_session_name = _tmux_curriculum_session_name(curriculum_id)

    cmd = _build_spawn_command(
        agent,
        sketch_id=sketch_id if agent == "claude" else None,
        curriculum_id=curriculum_id if agent == "claude" else None,
        resume_session=resume_session,
        bypass=bypass and agent == "claude",
    )
    binary = shutil.which(cmd[0])
    if not binary:
        await ws.send_bytes(f"\x1b[31m{agent} is not installed.\x1b[0m\r\n".encode())
        await ws.close(code=4001, reason=f"{agent} not found")
        return

    # Create PTY pair
    master_fd, slave_fd = pty.openpty()
    winsize = struct.pack("HHHH", 30, 120, 0, 0)
    fcntl.ioctl(master_fd, termios.TIOCSWINSZ, winsize)

    env = os.environ.copy()
    env["TERM"] = "xterm-256color"

    proc = subprocess.Popen(
        cmd,
        stdin=slave_fd,
        stdout=slave_fd,
        stderr=slave_fd,
        cwd=str(PROJECT_ROOT.resolve()),
        env=env,
        close_fds=True,
        start_new_session=True,
    )
    os.close(slave_fd)

    # 새 sketch 세션이면 백그라운드로 새 .jsonl 파일 감지해서 DB 업데이트
    if agent == "claude" and sketch_id is not None and resume_session is None:
        detect_task = asyncio.create_task(_detect_new_session(pre_sessions, sketch_id))

    loop = asyncio.get_event_loop()
    running = True

    async def read_pty():
        while running:
            try:
                readable = await loop.run_in_executor(
                    None, lambda: select.select([master_fd], [], [], 0.05)[0]
                )
                if readable:
                    data = os.read(master_fd, 16384)
                    if not data:
                        break
                    await ws.send_bytes(data)
            except (OSError, WebSocketDisconnect):
                break

    read_task = asyncio.create_task(read_pty())

    try:
        while True:
            msg = await ws.receive()

            if msg.get("type") == "websocket.disconnect":
                break

            if "text" in msg:
                data = json.loads(msg["text"])
                if data.get("type") == "resize":
                    # 프론트에서 간혹 NaN/Infinity 가 들어온다 (탭 전환으로 xterm
                    # 컨테이너가 display:none → 0×0 이 되면 proposeDimensions 가
                    # cellWidth=0 나눗셈 때문에 비정상 값을 뱉는 경우). 그대로
                    # struct.pack 하면 예외가 핸들러를 탈출해 WS 가 닫히고
                    # tmux 세션까지 detach 된다. 유효하지 않은 크기는 조용히 무시.
                    try:
                        cols = int(data.get("cols", 120))
                        rows = int(data.get("rows", 30))
                    except (TypeError, ValueError):
                        continue
                    if not (0 < cols <= 1000 and 0 < rows <= 1000):
                        continue
                    winsize = struct.pack("HHHH", rows, cols, 0, 0)
                    fcntl.ioctl(master_fd, termios.TIOCSWINSZ, winsize)
                elif data.get("type") == "input":
                    os.write(master_fd, data["data"].encode())
            elif "bytes" in msg:
                os.write(master_fd, msg["bytes"])

    except WebSocketDisconnect:
        pass
    finally:
        running = False
        read_task.cancel()
        if detect_task and not detect_task.done():
            detect_task.cancel()

        if tmux_session_name is not None:
            # tmux 에 래핑된 sketch 세션: detach 만 해서 claude 프로세스가
            # tmux 서버 안에서 계속 살아있게 한다. 우리 proc 는 tmux 클라이언트
            # 이므로 detach 시 자연스럽게 종료됨.
            try:
                subprocess.run(
                    _tmux_base_cmd() + ["detach-client", "-s", tmux_session_name],
                    capture_output=True,
                    timeout=3,
                )
            except Exception:
                pass
            try:
                proc.wait(timeout=3)
            except Exception:
                proc.kill()
        else:
            try:
                proc.terminate()
                proc.wait(timeout=3)
            except Exception:
                proc.kill()

        try:
            os.close(master_fd)
        except OSError:
            pass
