"""WebSocket endpoint that spawns a coding agent CLI session (Claude Code or OpenCode) with MCP tools."""

import asyncio
import json
import os
import pty
import select
import shutil
import struct
import subprocess
import fcntl
import termios
from pathlib import Path

import aiosqlite
from fastapi import APIRouter, WebSocket, WebSocketDisconnect, Query

from src.backend.config import get_settings
from src.backend.database import get_connection

router = APIRouter(tags=["terminal"])

PROJECT_ROOT = Path(__file__).parent.parent.parent.parent
DATA_DIR = PROJECT_ROOT / "data"


def _claude_sessions_dir() -> Path:
    """Where Claude Code stores per-project session .jsonl files."""
    encoded = str(PROJECT_ROOT.resolve()).replace("/", "-")
    return Path.home() / ".claude" / "projects" / encoded


def _list_session_uuids() -> set[str]:
    d = _claude_sessions_dir()
    if not d.exists():
        return set()
    return {p.stem for p in d.glob("*.jsonl")}


async def _detect_new_session(
    pre: set[str],
    sketch_id: int,
    deadline_seconds: float = 8.0,
):
    """Poll the Claude sessions dir for a new .jsonl file and save its uuid to the sketch."""
    settings = get_settings()
    elapsed = 0.0
    while elapsed < deadline_seconds:
        await asyncio.sleep(0.5)
        elapsed += 0.5
        current = _list_session_uuids()
        new_ids = current - pre
        if new_ids:
            session_id = sorted(new_ids)[0]  # 보통 1개
            db = await get_connection(settings.db_path)
            try:
                await db.execute(
                    "UPDATE sketches SET claude_session_id = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND claude_session_id IS NULL",
                    (session_id, sketch_id),
                )
                await db.commit()
            finally:
                await db.close()
            return


async def _get_sketch_session(sketch_id: int) -> str | None:
    settings = get_settings()
    db = await get_connection(settings.db_path)
    try:
        cursor = await db.execute(
            "SELECT claude_session_id FROM sketches WHERE id = ?", (sketch_id,)
        )
        row = await cursor.fetchone()
        return row["claude_session_id"] if row else None
    finally:
        await db.close()


def _find_python() -> tuple[str, list[str]]:
    """Return (command, base_args) for running our MCP server."""
    venv_python = PROJECT_ROOT.resolve() / ".venv" / "bin" / "python"
    if venv_python.exists():
        return str(venv_python), ["-m", "src.backend.mcp_server.server"]
    return "uv", ["run", "python", "-m", "src.backend.mcp_server.server"]


def _ensure_claude_mcp_config() -> Path:
    """Generate Claude Code MCP config (mcpServers format)."""
    command, args = _find_python()
    config = {
        "mcpServers": {
            "dojang": {
                "command": command,
                "args": args,
                "cwd": str(PROJECT_ROOT.resolve()),
            }
        }
    }
    path = DATA_DIR / "mcp_config.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(config, indent=2))
    return path


def _ensure_opencode_config() -> Path:
    """Generate opencode.json in project root (mcp format for OpenCode)."""
    command, args = _find_python()
    config = {
        "mcp": {
            "dojang": {
                "type": "local",
                "command": [command, *args],
                "enabled": True,
            }
        }
    }
    path = PROJECT_ROOT / "opencode.json"
    path.write_text(json.dumps(config, indent=2))
    return path


# ---------------------------------------------------------------------------
# tmux wrapping for sketch terminals
#
# Sketch 터미널은 탭을 떠나면 WebSocket 이 끊기고, 돌아오면 새 WS 가 연결된다.
# tmux 로 감싸면 (a) 스크롤백이 보존되고, (b) 탭 떠나있는 동안에도 claude 가
# 계속 일할 수 있다 (긴 답변/도구 호출이 중단되지 않음).
#
# 격리된 소켓 (-L dojang) 을 써서 혹시 호스트에 떠있는 다른 tmux 와 섞이지
# 않게 한다. 키바인딩은 전부 unbind 해서 "투명 래퍼" 로 동작하도록.
# ---------------------------------------------------------------------------

_TMUX_SOCKET = "dojang"
_TMUX_CONF_PATH = DATA_DIR / "tmux.conf"
_TMUX_CONF = """# auto-generated by Dojang backend
set -g prefix None
unbind-key -a
set -g status off
set -sg escape-time 0
set -g default-terminal "xterm-256color"
set -g history-limit 50000
set-window-option -g aggressive-resize on
"""


def _ensure_tmux_conf() -> Path:
    _TMUX_CONF_PATH.parent.mkdir(parents=True, exist_ok=True)
    if not _TMUX_CONF_PATH.exists() or _TMUX_CONF_PATH.read_text() != _TMUX_CONF:
        _TMUX_CONF_PATH.write_text(_TMUX_CONF)
    return _TMUX_CONF_PATH


def _tmux_base_cmd() -> list[str]:
    return ["tmux", "-L", _TMUX_SOCKET, "-f", str(_ensure_tmux_conf())]


def _tmux_has_session(name: str) -> bool:
    result = subprocess.run(
        _tmux_base_cmd() + ["has-session", "-t", name],
        capture_output=True,
    )
    return result.returncode == 0


def _tmux_sketch_session_name(sketch_id: int) -> str:
    return f"dojang-sketch-{sketch_id}"


# 컨테이너의 Claude Code 세션이 /app/CLAUDE.md 를 자동으로 시스템 프롬프트에
# 주입받도록 한다 — 세션이 "맥락" 질문을 받았을 때 data/current_context.md 를
# 읽어 학습자가 지금 뭘 보고 있는지 답하게 만드는 게 목적.
_CLAUDE_MD_MARKER = "<!-- auto-generated by Dojang backend -->"
_CLAUDE_MD_CONTENT = f"""{_CLAUDE_MD_MARKER}

# Dojang 세션

여기는 Dojang 학습 플랫폼 안에서 돌고 있는 Claude Code 세션입니다. 학습자는
sketch 노트, 연습문제, 지식 카드 같은 걸 열어놓고 당신과 대화합니다.

## 학습자의 현재 맥락 (중요)

학습자가 프론트엔드에서 지금 보고 있는 항목은 `data/current_context.md` 파일에
자동으로 기록됩니다. 다음 상황에서는 반드시 먼저 이 파일을 `Read` 로 읽어서
학습자의 현재 맥락을 확인하세요:

- 새 대화가 시작될 때 (첫 유저 메시지 직후)
- 사용자가 "맥락", "context", "지금 뭐 보고 있어" 처럼 현재 상황을 물을 때
- 사용자가 "이거", "이 문제", "여기" 같이 지시대명사로 무언가를 가리킬 때

파일 포맷:
- `@sketch:<제목> #<id>` + 본문 — 학습자가 열어둔 sketch 노트
- `@exercise:<제목> #<id>` — 학습자가 클릭한 연습문제
- `@knowledge:<제목> #<id>` — 학습자가 클릭한 지식 카드
- `> <인용>` — 학습자가 드래그해서 추가한 관심 포인트

파일이 비어있으면 지금 활성 맥락이 없다는 뜻입니다.

## MCP 도구 (dojang 서버)

커리큘럼/연습문제/지식을 조작할 때는 `dojang` MCP 서버의 도구를 쓰세요:
`get_curriculum`, `add_subject`, `create_exercise`, `create_curriculum`,
`save_knowledge`, `list_knowledge`, `execute_code`, `get_progress`. 데이터
변경 후 UI 갱신은 각 도구가 내부적으로 처리하므로 별도 알림 호출은 필요 없어요.
"""


def _ensure_container_claude_md() -> None:
    """컨테이너 안에서 돌 때만 /app/CLAUDE.md 를 써서 Claude Code 에게
    `data/current_context.md` 의 존재를 알려준다. 호스트 (레포 루트) 에는
    이미 프로젝트용 CLAUDE.md 가 있으므로, PROJECT_ROOT 가 /app 인 경우에만
    작동시켜 덮어쓰기를 방지한다. 또한 마커가 없는 기존 파일은 건드리지 않는다.
    """
    if str(PROJECT_ROOT) != "/app":
        return
    target = PROJECT_ROOT / "CLAUDE.md"
    if target.exists():
        existing = target.read_text()
        if not existing.startswith(_CLAUDE_MD_MARKER):
            return  # 사람이 쓴 CLAUDE.md 는 손대지 않음
        if existing == _CLAUDE_MD_CONTENT:
            return  # 이미 최신
    target.write_text(_CLAUDE_MD_CONTENT)


def _build_spawn_command(
    agent: str,
    sketch_id: int | None = None,
    resume_session: str | None = None,
) -> list[str]:
    """Return the CLI command to spawn for the given agent type.

    Sketch 터미널 (sketch_id 가 있는 경우) 은 tmux 로 감싸서 WS 재연결 사이에
    세션과 스크롤백이 유지되게 한다. 기존 tmux 세션이 있으면 attach 하고,
    없으면 새로 만든다. 전역 (Learn) 터미널은 현재 동작 유지.
    """
    if agent == "opencode":
        _ensure_opencode_config()
        return ["opencode"]

    _ensure_container_claude_md()
    mcp_config = _ensure_claude_mcp_config()
    claude_cmd = ["claude", "--mcp-config", str(mcp_config)]
    if resume_session:
        claude_cmd += ["--resume", resume_session]

    if sketch_id is None:
        return claude_cmd

    session_name = _tmux_sketch_session_name(sketch_id)
    if _tmux_has_session(session_name):
        # 살아있는 tmux 세션 재접속 — 다른 client 는 강제 detach (-d) 해서
        # 동시 접속으로 인한 이상한 리사이즈 방지.
        return _tmux_base_cmd() + ["attach-session", "-d", "-t", session_name]

    # 첫 연결 or tmux 서버 재시작 후 — claude 를 새 tmux 세션 안에서 띄운다.
    return _tmux_base_cmd() + ["new-session", "-s", session_name, *claude_cmd]


@router.get("/api/agents")
async def list_agents():
    """Return available agents and their install status."""
    agents = []
    for name, cmd in [("claude", "claude"), ("opencode", "opencode")]:
        agents.append({
            "id": name,
            "label": "Claude Code" if name == "claude" else "OpenCode",
            "installed": shutil.which(cmd) is not None,
        })
    return agents


@router.websocket("/ws/terminal")
async def terminal_websocket(
    ws: WebSocket,
    agent: str = Query(default="claude"),
    sketch_id: int | None = Query(default=None),
):
    await ws.accept()

    if agent not in ("claude", "opencode"):
        await ws.close(code=4000, reason=f"Unknown agent: {agent}")
        return

    # Per-sketch session tracking (claude only)
    resume_session: str | None = None
    pre_sessions: set[str] = set()
    detect_task: asyncio.Task | None = None
    tmux_session_name: str | None = None
    if agent == "claude" and sketch_id is not None:
        resume_session = await _get_sketch_session(sketch_id)
        if resume_session is None:
            pre_sessions = _list_session_uuids()  # 새 세션이면 spawn 후 diff로 잡음
        tmux_session_name = _tmux_sketch_session_name(sketch_id)

    cmd = _build_spawn_command(
        agent,
        sketch_id=sketch_id if agent == "claude" else None,
        resume_session=resume_session,
    )
    binary = shutil.which(cmd[0])
    if not binary:
        await ws.send_bytes(f"\x1b[31m{agent} is not installed.\x1b[0m\r\n".encode())
        await ws.close(code=4001, reason=f"{agent} not found")
        return

    # Create PTY pair
    master_fd, slave_fd = pty.openpty()
    winsize = struct.pack("HHHH", 30, 120, 0, 0)
    fcntl.ioctl(master_fd, termios.TIOCSWINSZ, winsize)

    env = os.environ.copy()
    env["TERM"] = "xterm-256color"

    proc = subprocess.Popen(
        cmd,
        stdin=slave_fd,
        stdout=slave_fd,
        stderr=slave_fd,
        cwd=str(PROJECT_ROOT.resolve()),
        env=env,
        close_fds=True,
        start_new_session=True,
    )
    os.close(slave_fd)

    # 새 sketch 세션이면 백그라운드로 새 .jsonl 파일 감지해서 DB 업데이트
    if agent == "claude" and sketch_id is not None and resume_session is None:
        detect_task = asyncio.create_task(_detect_new_session(pre_sessions, sketch_id))

    loop = asyncio.get_event_loop()
    running = True

    async def read_pty():
        while running:
            try:
                readable = await loop.run_in_executor(
                    None, lambda: select.select([master_fd], [], [], 0.05)[0]
                )
                if readable:
                    data = os.read(master_fd, 16384)
                    if not data:
                        break
                    await ws.send_bytes(data)
            except (OSError, WebSocketDisconnect):
                break

    read_task = asyncio.create_task(read_pty())

    try:
        while True:
            msg = await ws.receive()

            if msg.get("type") == "websocket.disconnect":
                break

            if "text" in msg:
                data = json.loads(msg["text"])
                if data.get("type") == "resize":
                    cols = data.get("cols", 120)
                    rows = data.get("rows", 30)
                    winsize = struct.pack("HHHH", rows, cols, 0, 0)
                    fcntl.ioctl(master_fd, termios.TIOCSWINSZ, winsize)
                elif data.get("type") == "input":
                    os.write(master_fd, data["data"].encode())
            elif "bytes" in msg:
                os.write(master_fd, msg["bytes"])

    except WebSocketDisconnect:
        pass
    finally:
        running = False
        read_task.cancel()
        if detect_task and not detect_task.done():
            detect_task.cancel()

        if tmux_session_name is not None:
            # tmux 에 래핑된 sketch 세션: detach 만 해서 claude 프로세스가
            # tmux 서버 안에서 계속 살아있게 한다. 우리 proc 는 tmux 클라이언트
            # 이므로 detach 시 자연스럽게 종료됨.
            try:
                subprocess.run(
                    _tmux_base_cmd() + ["detach-client", "-s", tmux_session_name],
                    capture_output=True,
                    timeout=3,
                )
            except Exception:
                pass
            try:
                proc.wait(timeout=3)
            except Exception:
                proc.kill()
        else:
            try:
                proc.terminate()
                proc.wait(timeout=3)
            except Exception:
                proc.kill()

        try:
            os.close(master_fd)
        except OSError:
            pass
